# Generated by Django 5.1.3 on 2024-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_perfumedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumedetails',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
