# Generated by Django 5.1.3 on 2025-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_perfumedetails_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumedetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='perfumedetails',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
