# Generated by Django 5.1.3 on 2025-07-08 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_perfumedetails_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumedetails',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfume_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
